# Generated by Django 2.2.1 on 2019-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('customer_name', models.CharField(max_length=50)),
                ('prodect_order', models.IntegerField()),
                ('cus_amount', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
    ]
