# Generated by Django 2.2.1 on 2019-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragadasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_file', models.FileField(max_length=30, upload_to='')),
            ],
        ),
    ]
