# Generated by Django 2.2.1 on 2019-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragadasapp', '0002_choosefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progadas',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
